config/routes.rb
Rails.application.routes.draw do
  get 'payments/create'
  get 'payments/capture'
  get '/offers/index', to: redirect('/')
  get 'offers/show'
  get 'projects/index'
  get 'projects/show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root to: 'offers#index'

  resources :offers
  resources :projects

  get '/scroll_animator', to: 'scroll_animator#index'
  get '/offers/index', to: 'offers#index'
  get '/offers/show', to: 'offers#show'
  get '/projects/index', to: 'projects#index'
  get '/projects/show', to: 'projects#show'
  get '/offers/index', to: 'offers#index'
  get 'contact', to: 'pages#contact'
  get 'mentions_legales', to: 'pages#mentions_legales'
  post '/payments/create', to: 'payments#create'
  post '/payments/capture', to: 'payments#capture'



  post '/contact', to: 'contacts#create', as: 'contact_submission'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/offer.rb
class Offer < ApplicationRecord
  monetize :price_cents
end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private

  def record_not_found
    redirect_to root_path, alert: "L'enregistrement demandé n'a pas été trouvé."
  end
end

app/controllers/contacts_controller.rb
# app/controllers/contacts_controller.rb

class ContactsController < ApplicationController
  def create
    # Récupérer les données du formulaire
    name = params[:name]
    email = params[:_replyto]
    message = params[:message]

    # Valider l'e-mail
    if valid_email?(email)
      # Le reste de votre logique pour traiter le formulaire
      # ...
      # ...

      # Par exemple, vous pouvez afficher un message de succès
      flash[:notice] = "Votre message a été envoyé avec succès !"
    else
      # En cas d'e-mail invalide, afficher un message d'erreur
      flash[:alert] = "Veuillez entrer une adresse e-mail valide."
    end

    # Rediriger vers une page appropriée
    redirect_to root_path
  end

  private

  def valid_email?(email)
    # Utilisez une expression régulière pour valider l'e-mail
    # Cette expression est plus simple que celle utilisée dans le HTML
    email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    email =~ email_regex
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  # Appelle set_offer avant les actions spécifiées, ici uniquement :show pour l'instant.
  # Ajoutez d'autres actions comme :edit, :update, :destroy si vous avez ces vues et souhaitez sécuriser l'accès à une offre spécifique.
  before_action :set_offer, only: [:show]

  def index
    # Récupère toutes les offres et tous les projets pour les afficher sur la page index
    @offers = Offer.all
    @projects = Project.all
  end

  def show
    # L'offre spécifique @offer est déjà définie grâce à set_offer appelé par before_action
    # Aucun code supplémentaire n'est nécessaire ici si la vue show utilise simplement @offer
    # Dans votre contrôleur Rails, par exemple dans OffersController#show

  end

  private

  # Définit @offer en utilisant l'ID fourni dans les paramètres de la requête
  def set_offer
    @offer = Offer.find(params[:id])
  end

  def generate_client_token
    # pass client_token to your front-end
    @client_token = gateway.client_token.generate(
      :customer_id => a_customer_id
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
    # Vous pouvez définir des variables d'instance ici pour les passer à la vue si nécessaire
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show]

  def index
    @projects = Project.all
  end

  def show
    unless Project.exists?(params[:id])
      redirect_to projects_path, alert: "Projet non trouvé."
      return
    end

    @project = Project.find(params[:id])
  end


  private

  def set_project
    @project = Project.find_by(id: params[:id])
    redirect_to(projects_path, alert: "Projet non trouvé.") unless @project
  end

end

app/controllers/scroll_animator_controller.rb
class ScrollAnimatorController < ApplicationController
  def index
    # Récupérer des données à partir de la base de données
    offers = Offer.all

    # Répondre avec les données au format JSON
    render json: offers
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/geocodings_helper.rb
module GeocodingsHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/scroll_animator_helper.rb
module ScrollAnimatorHelper
end

app/views/offers/show.html.erb
<head>
  <meta charset="UTF-8">
  <meta name="description" content="<%= @offer.description %>">
  <meta property="og:title" content="SDN | <%= @offer.title %>">
  <meta property="og:description" content="<%= @offer.description %>">
  <meta property="og:type" content="website">
  <meta property="og:image" content="<%= @offer.image_url %>">
  <title>SDN | <%= @offer.title %></title>
  <script src="https://www.paypal.com/sdk/js?client-id=BAA8R3BOfDl2leQhYFnkI0LH2NQyWhTgk7qV1X2CcqnBibC6akO8NIzwv_nLKVC2gSXZiFx263OsZx3hbs&components=hosted-buttons&disable-funding=venmo&currency=EUR"></script>

</head>

<body>
<br><br>
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8 mb-4">
      <div class="row"> <!-- Nouvelle ligne pour la disposition côte à côte -->
        <!-- Colonne pour la card -->
        <div class="col-md-9">
          <% if @offer.image_url.present? %>
            <video class="img-fluid" autoplay loop muted>
              <source src="<%= @offer.image_url %>" type="video/mp4">
              Votre navigateur ne supporte pas la balise vidéo.
            </video>
          <% end %>
          <br>
          <h2 class="offer-title text-center"><%= @offer.title %></h2>
          <div class="offer-price mt-2 text-center">
            <h5><%= number_to_currency(@offer.price, unit: "€") %></h5>
          </div>
          <p class="offer-description text-center"><%= @offer.description %></p>
          <% if @offer.title == "Web App" %> <!-- Condition pour afficher le bouton Contacter -->
            <div class="text-center mt-3 mb-3">
              <a class="btn btn-primary" href="<%= contact_path %>">Contacter</a>
            </div>
          <% end %>
          <p class="card-text-info card-description text-center">
                  <% if @offer.duration == 0 %>
                    <i class="fa-solid fa-clock"></i> <strong> à définir</strong>
                  <% else %>
                    <i class="fa-solid fa-clock"></i> <strong> environ <%= @offer.duration %> jours</strong>
                  <% end %> <br>
        </div>
        <!-- Colonne pour le bouton PayPal -->
        <div class="col-md-3 d-flex align-items-center" id="paypal">
          <div id="paypal-container-WYVAED5YAJ94Q" class="w-100"></div> <!-- Assurez-vous que le conteneur PayPal est adapté à la largeur -->
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div id="modal" class="modal">
  <div class="modal-content text-center">
    <span class="close" onclick="fermerModal()">&times;</span>
    <h5 class="textmodal text-center purple"><strong>N'oubliez pas ! 😉</strong></h2>
    <p class="textmodal"><strong>Après votre achat, veuillez m'envoyer un message via le formulaire de contact pour me donner une description de votre idée ou projet.</strong></p>
  </div>
</div>

</body>


<script>
  paypal.HostedButtons({
    hostedButtonId: "WYVAED5YAJ94Q",
  }).render("#paypal-container-WYVAED5YAJ94Q")
</script>

<script>
// Fonction pour afficher le modal
function afficherModal() {
  var modal = document.getElementById("modal");
  modal.style.display = "block";
}

// Fonction pour fermer le modal
function fermerModal() {
  var modal = document.getElementById("modal");
  modal.style.display = "none";
}

// Appeler la fonction afficherModal() lorsque la page est chargée
window.onload = function() {
  afficherModal();
};
</script>
</html>

app/views/pages/contact.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact | SDN</title>
    <meta name="description" content="Vous avez des questions ou des commentaires ? N'hésitez pas à me contacter en utilisant le formulaire ci-dessous.">
      <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://www.stephanedn.com/contact">
    <meta property="og:title" content="Contact | SDN">
    <meta property="og:description" content="Vous avez des questions ou des commentaires ? N'hésitez pas à me contacter en utilisant le formulaire ci-dessous.">
    <meta property="og:image" content="https://i.ibb.co/TbPC1yW/DALL-E-2024-04-04-00-30-01-Illustration-of-a-male-avatar-sitting-at-a-desk-with-a-computer-coding.jpg">

    <!-- CSRF et CSP Meta tags supprimés pour Formspree -->
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.2.0/uicons-solid-rounded/css/uicons-solid-rounded.css'>
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.2.0/uicons-regular-rounded/css/uicons-regular-rounded.css'>
</head>
<body>
    <div class="container mt-5">
        <h5 class="welcome-title">Contactez-moi</h5>
        <p class="text-center"><strong>Vous avez des questions ou des commentaires ? N'hésitez pas à me contacter en utilisant le formulaire ci-dessous.</strong></p>
        <form id="contact-form" action="https://formspree.io/f/myyrbygq" method="POST">
            <!-- Suppression de la ligne du token CSRF -->
            <div class="form-group">
                <i class="fa-solid fa-user"></i> <label for="name">Nom</label>
                <input type="text" class="form-control" id="name" autocomplete="name" name="name" required>
            </div>
            <br>
            <div class="form-group">
                <i class="fi fi-sr-envelope"></i> <label for="email">Email</label>
                <input type="email" class="form-control" id="email" autocomplete="email" name="_replyto" title="Veuillez entrer une adresse e-mail valide." required>
            </div>
            <br>
            <div class="form-group">
                <i class="fi fi-rr-edit"></i> <label for="message">Message</label>
                <textarea class="form-control" id="message" name="message" rows="3" required></textarea>
            </div>
            <br>
            <button type="submit" class="btn btn-primary custom-btn">Envoyer</button>
        </form>
    </div>

    <!-- Remplacement de jQuery Slim par la version complète si `matchHeight` est nécessaire -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <!-- Inclure ici le script pour `matchHeight` si nécessaire -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
<script>
document.addEventListener("DOMContentLoaded", function() {
    var form = document.getElementById('contact-form');

    // Restauration des valeurs sauvegardées
    document.querySelectorAll('#contact-form input, #contact-form textarea').forEach(input => {
        const savedValue = localStorage.getItem(input.id);
        if (savedValue) input.value = savedValue;
    });

    // Sauvegarde des valeurs lors de l'entrée
    form.addEventListener('input', (e) => {
        localStorage.setItem(e.target.id, e.target.value);
    });

    form.addEventListener('submit', async function(event) {
        event.preventDefault(); // Empêche le comportement de soumission par défaut du formulaire

        var formData = new FormData(form);
        try {
            var response = await fetch(form.action, {
                method: form.method,
                body: formData,
                headers: {'Accept': 'application/json'}
            });

            if (response.ok) {
                alert("Merci pour votre message. Nous vous contacterons bientôt !");
                form.reset();
                localStorage.clear();
            } else {
                alert("Oups ! Il y a eu un problème avec l'envoi de votre formulaire. Veuillez réessayer.");
            }
        } catch (error) {
            console.error('Erreur lors de l’envoi du formulaire : ', error);
            alert("Oups ! Il y a eu un problème avec l'envoi de votre formulaire. Veuillez réessayer.");
        }
    });
});
</script>
</html>

app/views/pages/mentions_legales.html.erb
<br>
<br>
<div class="text-center">
  <h1>Mentions légales</h1>
  <br>

  <h2>1. Éditeur du site</h2>
  <p>Le site web est édité par Stéphane Dei-Negri, domicilié au 31 route de Madirac, 33880 Saint-Caprais de Bordeaux, France. Email: s.deinegri2@gmail.com</a>.</p>
     <br>
  <h2>2. Propriété intellectuelle</h2>
  <p>Tout le contenu présent sur ce site, incluant, sans limitation, les graphiques, images, textes, vidéos, animations, sons, logos, gifs et icônes ainsi que leur mise en forme sont la propriété exclusive de la société à l'exception des marques, logos ou contenus appartenant à d'autres sociétés partenaires ou auteurs. Toute reproduction, distribution, modification, adaptation, retransmission ou publication, même partielle, de ces différents éléments est strictement interdite sans l'accord exprès par écrit de Stéphane Dei-Negri. Cette représentation ou reproduction, par quelque procédé que ce soit, constitue une contrefaçon sanctionnée par les articles L.335-2 et suivants du Code de la propriété intellectuelle. Le non-respect de cette interdiction constitue une contrefaçon pouvant engager la responsabilité civile et pénale du contrefacteur.</p>
    <br>
  <h2>3. Gestion des données personnelles</h2>
  <p>Les données personnelles collectées sur le site sont principalement utilisées par l'éditeur pour la gestion des relations avec vous, et le cas échéant pour le traitement de vos commandes. Les données collectées sont conservées pour une durée maximale d’un an. Conformément à la loi « informatique et libertés », vous bénéficiez d’un droit d’accès, de rectification et d’opposition aux informations qui vous concernent, que vous pouvez exercer en vous adressant à l'adresse email de l'éditeur.</p>
    <br>
  <h2>4. Cookies</h2>
  <p>Le site utilise des cookies uniquement pour assurer son bon fonctionnement et optimiser la performance technique. Ces fichiers texte stockés sur votre ordinateur permettent une analyse de l'utilisation du site et de mesurer l'audience. Les informations collectées via les cookies ne permettent en aucun cas d'identifier personnellement un utilisateur.</p>
    <br>
  <h2>5. Conditions de service</h2>
  <p>Ce site est proposé en langues HTML5 et CSS3, pour un meilleur confort d'utilisation et un graphisme plus agréable. Nous recommandons l’utilisation de navigateurs modernes comme Internet Explorer, Safari, Firefox, Google Chrome, etc.</p>
    <br>
  <h2>6. Contact</h2>
  <p>Pour toute question ou demande d'information concernant le site, ou tout signalement de contenu ou d’activités illicites, l'utilisateur peut contacter l'éditeur à l’adresse suivante : s.deinegri2@gmail.com ou par courrier recommandé avec accusé de réception adressé à l'éditeur aux coordonnées spécifiées dans ce document.</p>
    <br>
</div>

app/views/projects/show.html.erb
<head>
  <meta charset="UTF-8">

  <meta name="description" content="<%= @project.description %>">
  <meta property="og:title" content="SDN | <%= @project.title %>">
  <meta property="og:description" content="<%= @project.description %>">
  <meta property="og:type" content="website">
  <meta property="og:image" content="<%= @project.image_url %>">
  <title>SDN | <%= @project_title %></title>
</head>
<body>
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="project-show text-center">
        <% if @project.image_url.present? %>
          <video class="img-fluid" autoplay loop muted>
            <source src="<%= @project.image_url %>" type="video/mp4">
            Votre navigateur ne supporte pas la balise vidéo.
          </video>
        <% end %>
        <div class="project-details mt-3">
          <h2 class="project-title"><%= @project.title %></h2>

          <div class="project-category">
            <h5>
              <% case @project.category %>
              <% when "Site Portfolio" %>
                <i class="fas fa-briefcase"></i> <%= @project.category %>
              <% when "Web App" %>
                <i class="fas fa-mobile-alt"></i> <%= @project.category %>
              <% when "Logo Pro" %>
                <i class="fa-solid fa-pencil"></i> <%= @project.category %>
              <% else %>
                <%= @project.category %>
              <% end %>
            </h5>
          </div>
          <br>
          <p class="project-description"><%= raw @project.description %></p>
        </div>
      </div>
      <br>
      <div class="social-share">
        <p>Partager :</p>
        <%= link_to raw('<i class="fa-brands fa-x-twitter"></i>'), "https://twitter.com/intent/tweet?text=#{CGI.escape('Découvrez ce projet: ' + project_url(@project))}", target: "_blank", class: "twitter-share-button" %>
        <%= link_to raw('<i class="fa-brands fa-facebook"></i>'), "https://www.facebook.com/sharer/sharer.php?u=#{CGI.escape(project_url(@project, host: request.host_with_port))}", target: "_blank", class: "facebook-share-button" %>
        <%= link_to raw('<i class="fa-brands fa-linkedin"></i>'), "https://www.linkedin.com/shareArticle?mini=true&url=#{CGI.escape(project_url(@project, host: request.host_with_port))}", target: "_blank", class: "linkedin-share-button" %>
      </div>
    </div>
  </div>
</div>
</body>


<script>
document.addEventListener('DOMContentLoaded', function() {
    // Twitter
    document.querySelectorAll('.twitter-share-button').forEach(function(button) {
      button.addEventListener('click', function(e) {
        e.preventDefault();
        window.open(this.href, 'twitter-share', 'width=550,height=235');
      });
    });

    // Facebook
    document.querySelectorAll('.facebook-share-button').forEach(function(button) {
      button.addEventListener('click', function(e) {
        e.preventDefault();
        window.open(this.href, 'facebook-share', 'toolbar=0,status=0,width=626,height=436');
      });
    });

    // LinkedIn
    document.querySelectorAll('.linkedin-share-button').forEach(function(button) {
      button.addEventListener('click', function(e) {
        e.preventDefault();
        window.open(this.href, 'linkedin-share', 'width=550,height=600');
      });
    });
});
</script>